# Generated by Django 5.1.1 on 2024-09-16 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pothole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_description", models.TextField(blank=True, null=True)),
                ("alternate_description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="pothole_images/")),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="pothole_videos/"
                    ),
                ),
                ("location_lat", models.FloatField()),
                ("location_lon", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
