# Generated by Django 5.1.1 on 2024-09-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("potholes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pothole",
            old_name="location_lat",
            new_name="latitude",
        ),
        migrations.RenameField(
            model_name="pothole",
            old_name="location_lon",
            new_name="longitude",
        ),
        migrations.RemoveField(
            model_name="pothole",
            name="ai_description",
        ),
        migrations.RemoveField(
            model_name="pothole",
            name="alternate_description",
        ),
        migrations.RemoveField(
            model_name="pothole",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="pothole",
            name="image",
        ),
        migrations.RemoveField(
            model_name="pothole",
            name="video",
        ),
        migrations.AddField(
            model_name="pothole",
            name="description",
            field=models.TextField(default="No description provided"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pothole",
            name="name",
            field=models.CharField(default="No description provided", max_length=100),
            preserve_default=False,
        ),
    ]
