# Generated by Django 5.1.1 on 2024-09-16 21:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("potholes", "0002_rename_location_lat_pothole_latitude_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pothole_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_description", models.CharField(max_length=100)),
                ("alternate_description", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name="pothole",
            old_name="latitude",
            new_name="location_lat",
        ),
        migrations.RenameField(
            model_name="pothole",
            old_name="longitude",
            new_name="location_lon",
        ),
        migrations.RemoveField(
            model_name="pothole",
            name="description",
        ),
        migrations.RemoveField(
            model_name="pothole",
            name="name",
        ),
        migrations.AddField(
            model_name="pothole",
            name="ai_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pothole",
            name="alternate_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pothole",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pothole",
            name="image",
            field=models.ImageField(
                default="No description provided", upload_to="pothole_images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pothole",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="pothole_videos/"),
        ),
    ]
