# Generated by Django 5.1.1 on 2024-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "potholes",
            "0003_pothole_model_rename_latitude_pothole_location_lat_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Pothole_model",
        ),
        migrations.AddField(
            model_name="pothole",
            name="destination",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pothole",
            name="origin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pothole",
            name="road_name",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pothole",
            name="road_type",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pothole",
            name="town_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
