# Generated by Django 5.1.1 on 2024-09-17 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("potholes", "0004_delete_pothole_model_pothole_destination_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PotholeReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_description", models.TextField()),
                ("alternate_description", models.TextField()),
                ("location_lat", models.FloatField(blank=True, null=True)),
                ("location_lon", models.FloatField(blank=True, null=True)),
                ("town_name", models.CharField(max_length=100)),
                ("road_type", models.CharField(max_length=50)),
                ("road_name", models.CharField(max_length=100)),
                ("origin", models.CharField(max_length=100)),
                ("destination", models.CharField(max_length=100)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Pothole",
        ),
    ]
